// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WikiPage_Stick : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WikiPage_Stick));
        
        string IMigrationMetadata.Id
        {
            get { return "201708011309530_WikiPage_Stick"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
